# Generated by Django 4.2.13 on 2026-05-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="패키지명")),
                ("credits", models.IntegerField(verbose_name="크레딧 수")),
                ("price", models.IntegerField(verbose_name="가격(원)")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "크레딧 패키지",
                "verbose_name_plural": "크레딧 패키지 목록",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="잔여 크레딧")),
                (
                    "free_used_this_month",
                    models.IntegerField(default=0, verbose_name="이번달 무료 사용"),
                ),
                (
                    "free_reset_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="무료 초기화일"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 크레딧",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="주문번호"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="결제금액")),
                ("credits", models.IntegerField(verbose_name="충전 크레딧")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제대기"),
                            ("paid", "결제완료"),
                            ("failed", "결제실패"),
                            ("refunded", "환불"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "portone_payment_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="포트원 결제ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credits.creditpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "결제내역",
                "verbose_name_plural": "결제내역 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("charge", "충전"),
                            ("use", "사용"),
                            ("free", "무료사용"),
                            ("admin_grant", "관리자지급"),
                            ("refund", "환불"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="크레딧 수량")),
                ("balance_after", models.IntegerField(verbose_name="거래 후 잔액")),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.contentrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "크레딧 거래내역",
                "verbose_name_plural": "크레딧 거래내역 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
