# Generated by Django 4.2.13 on 2026-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpackage',
            name='is_analytics',
            field=models.BooleanField(default=False, verbose_name='분석데이터 가능'),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='is_auto_publish',
            field=models.BooleanField(default=False, verbose_name='자동발행 가능'),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='plan',
            field=models.CharField(choices=[('free', '무료'), ('starter', '스타터'), ('pro', '프로'), ('business', '비즈니스')], default='starter', max_length=20),
        ),
    ]
