# Generated by Django 4.2.13 on 2026-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', '무료'), ('starter', '스타터'), ('pro', '프로'), ('business', '비즈니스')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', '마스터'), ('admin', '관리자'), ('member', '멤버'), ('free', '무료회원')], default='free', max_length=20),
        ),
    ]
