# Generated by Django 4.2.13 on 2026-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plan_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '멤버')], max_length=20)),
                ('menu_key', models.CharField(max_length=50, verbose_name='메뉴 키')),
                ('menu_label', models.CharField(max_length=50, verbose_name='메뉴명')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '메뉴 권한',
                'verbose_name_plural': '메뉴 권한 목록',
                'ordering': ['role', 'order'],
                'unique_together': {('role', 'menu_key')},
            },
        ),
    ]
