# Generated by Django 4.2.13 on 2026-05-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="채널명")),
                ("slug", models.SlugField(unique=True, verbose_name="슬러그")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("video", "영상 자막"),
                            ("image", "이미지 카드"),
                        ],
                        max_length=20,
                        verbose_name="채널 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_auto_publish",
                    models.BooleanField(default=False, verbose_name="자동발행 가능"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("order", models.IntegerField(default=0, verbose_name="정렬순서")),
            ],
            options={
                "verbose_name": "채널",
                "verbose_name_plural": "채널 목록",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChannelPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_prompt", models.TextField(verbose_name="기본 프롬프트")),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="content.channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "채널 프롬프트",
                "verbose_name_plural": "채널 프롬프트 목록",
            },
        ),
        migrations.CreateModel(
            name="PromptOptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="그룹명")),
                ("label", models.CharField(max_length=50, verbose_name="화면표시명")),
                ("order", models.IntegerField(default=0, verbose_name="정렬순서")),
                (
                    "channel_prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_groups",
                        to="content.channelprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "옵션 그룹",
                "verbose_name_plural": "옵션 그룹 목록",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PromptOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="옵션명")),
                ("snippet", models.TextField(verbose_name="프롬프트 조각")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본선택"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬순서")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="content.promptoptiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "프롬프트 옵션",
                "verbose_name_plural": "프롬프트 옵션 목록",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="유형명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "콘텐츠 유형",
                "verbose_name_plural": "콘텐츠 유형 목록",
            },
        ),
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(verbose_name="입력 소재")),
                (
                    "selected_options",
                    models.JSONField(default=dict, verbose_name="선택된 옵션"),
                ),
                ("result_text", models.TextField(blank=True, verbose_name="생성 결과")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "생성중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "credit_used",
                    models.IntegerField(default=1, verbose_name="사용 크레딧"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.channel",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "콘텐츠 생성 이력",
                "verbose_name_plural": "콘텐츠 생성 이력 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="channelprompt",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_prompts",
                to="content.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="channelprompt",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channelprompt",
            unique_together={("content_type", "channel")},
        ),
    ]
