# Generated by Django 4.2.13 on 2026-06-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrequest',
            name='extra_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentrequest',
            name='text_card',
            field=models.ImageField(blank=True, null=True, upload_to='content/cards/'),
        ),
        migrations.AddField(
            model_name='contentrequest',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='content/thumbnails/'),
        ),
    ]
